const {
  INCOMING_QUEUE_NAME,
  INCOMING_QUEUE_URL,
  RESULT_TABLE_NAME,
  RESULT_TABLE_TTL_MINUTES,
} = process.env;

module.exports = {
  INCOMING_QUEUE_NAME,
  INCOMING_QUEUE_URL,
  RESULT_TABLE_NAME,
  RESULT_TABLE_TTL_MINUTES,
};
